Add style.css, scripts.js and index.html
jbej/OOP_11.6 pull request #1
Opened 2017-12-14 20:01 UTC by jbej

2017-12-17 14:04 UTC, matwjablonski requested changes
can you move card to empty column?

2017-12-17 14:04 UTC, matwjablonski commented on index.html
> +<html>
add attribute lang

2017-12-17 14:04 UTC, matwjablonski commented on index.html
> +
unnecessary empty line - to remove

2017-12-17 14:04 UTC, matwjablonski commented on index.html
> +
unnecessary empty line - to remove

2017-12-17 14:04 UTC, matwjablonski commented on scripts.js
> +            $columnAddCard.click(function() {
better use method `on` instead of `click` - in whole project

2017-12-18 10:04 UTC, jbej commented
Yes, I can move cards.

2017-12-18 13:14 UTC, matwjablonski approved these changes

2017-12-18 15:27 UTC, merged